Sync finished

diff --git a/dist-upload b/dist-upload
--- a/dist-upload
+++ b/dist-upload
@@ -89,7 +89,7 @@ do
             ;;
         e)  DEFAULT_RELEASE_PREFIX=$OPTARG;;
         l) ;;
-        u) ;;
+        u) UNDO="true";;
 
         y)  YES="true";;
     esac
@@ -254,25 +254,28 @@ if [[ "$S3_BUCKET" =~ ^[a-z][a-z0-9\-]+[a-z0-9]+$ ]]; then
 else
   echo "ERROR: Invalid bucket name!"; exit 1;
 fi
-# Checking whether the bucket exists on S3 and reachable with the given profile
-if aws s3 ls $S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'NoSuchBucket' ; then
-  echo "ERROR: The given S3 bucket '$S3_BUCKET' does not exists or not reachable with the credentials set in the profile '$PROFILE' !"; exit 1
-else
-  echo "    Bucket exists."
-fi
-# Checking write permission on bucket
-TEST_FILE="AWS_dist_configure_write_access_test.file"
-echo "AWS distribution write access TEST FILE - If you read this, you can delete this file any time." > $BASE_DIR/$TEST_FILE 
-if aws s3 cp $BASE_DIR/$TEST_FILE  s3://$S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'error' ; then
-  echo "ERROR: Bucket write test has failed. Check the permissions of the user!"; exit 1
-else
-  # Clean up backup file
-  aws s3 rm s3://$S3_BUCKET/$TEST_FILE --profile $PROFILE > /dev/null 2>&1
-  echo "    Bucket is verified."
-fi
-# Clean up local file
-rm $BASE_DIR/$TEST_FILE
 
+# If in write mode, then perform some tests
+if [ -n "$CONFIG_FILE_WRITE_MODE" ] ; then
+  # Checking whether the bucket exists on S3 and reachable with the given profile
+  if aws s3 ls $S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'NoSuchBucket' ; then
+    echo "ERROR: The given S3 bucket '$S3_BUCKET' does not exists or not reachable with the credentials set in the profile '$PROFILE' !"; exit 1
+  else
+    echo "    Bucket exists."
+  fi
+  # Checking write permission on bucket
+  TEST_FILE="AWS_dist_configure_write_access_test.file"
+  echo "AWS distribution write access TEST FILE - If you read this, you can delete this file any time." > $BASE_DIR/$TEST_FILE 
+  if aws s3 cp $BASE_DIR/$TEST_FILE  s3://$S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'error' ; then
+    echo "ERROR: Bucket write test has failed. Check the permissions of the user!"; exit 1
+  else
+    # Clean up backup file
+    aws s3 rm s3://$S3_BUCKET/$TEST_FILE --profile $PROFILE > /dev/null 2>&1
+    echo "    Bucket is verified."
+  fi
+  # Clean up local file
+  rm $BASE_DIR/$TEST_FILE
+fi  # testing if in write mode
 
 # If backup bucket is set or given as a param, check and set it too
 if [ -z "$CONFIG_FILE_WRITE_MODE" ] && [ -z BACKUP_BUCKET ] ; then
@@ -290,8 +293,8 @@ fi
 if [ -z "$BACKUP_BUCKET" ]; then
   BACKUP_BUCKET=$DEFAULT_BACKUP_BUCKET
 fi
-# If not switched off  and its name differs from main bucket, check it
-if [ -n "$BACKUP_BUCKET" ] && [ "$BACKUP_BUCKET" != "$S3_BUCKET" ] && [ "$BACKUP_BUCKET" != "same" ] && [ "$BACKUP_BUCKET" != "off"  ] ; then
+# If not switched off  and its name differs from main bucket, check it (if in write mode)
+if [ -n "$BACKUP_BUCKET" ] && [ "$BACKUP_BUCKET" != "$S3_BUCKET" ] && [ "$BACKUP_BUCKET" != "same" ] && [ "$BACKUP_BUCKET" != "off"  ] && [ -n "$CONFIG_FILE_WRITE_MODE" ] ; then
   # Checking the given bucket name format
   if [[ "$BACKUP_BUCKET" =~ ^[a-z][a-z0-9\-]+[a-z0-9]+$ ]]; then
     echo "  Using S3 bucket for backup: $BACKUP_BUCKET"
@@ -312,10 +315,10 @@ if [ -n "$BACKUP_BUCKET" ] && [ "$BACKUP_BUCKET" != "$S3_BUCKET" ] && [ "$BACKUP
   else
     # Clean up bucket file
     aws s3 rm s3://$BACKUP_BUCKET/$TEST_FILE --profile $PROFILE > /dev/null 2>&1
-    # We need to check, whether the bucket is empty (it can mess up the bucket otherwise)
-    BUCKET_CONTENT=`aws s3 ls --profile $PROFILE s3://$BACKUP_BUCKET`
+    # We need to check, whether the bucket is free of files (it can mess up the bucket otherwise)
+    BUCKET_CONTENT=`aws s3 ls --profile $PROFILE s3://$BACKUP_BUCKET | grep -v "/"`
     if [ -n "$BUCKET_CONTENT" ]; then
-      echo "ERROR: Bucket is not empty($BUCKET_CONTENT)! Only an empty bucket can be used for backup location."; exit 1
+      echo "ERROR: Bucket is not empty! Only an empty bucket can be used for backup location."; exit 1
     fi
     echo "    Backup bucket is verified."
   fi
@@ -335,60 +338,65 @@ else
   fi
 fi
 
-# Setting the version prefix if it is not set already (and backup is not set to 'off')
-if [ -z "$CONFIG_FILE_WRITE_MODE" ] && [ -z "$RELEASE_PREFIX" ]; then
+# If UNDO mode selected, leave this part out
+if [ -z "$UNDO" ]; then
+
+  # Setting the version prefix if it is not set already (and backup is not set to 'off')
+  if [ -z "$CONFIG_FILE_WRITE_MODE" ] && [ -z "$RELEASE_PREFIX" ]; then
+      RELEASE_PREFIX=$DEFAULT_RELEASE_PREFIX
+  fi
+  if [ -n "$CONFIG_FILE_WRITE_MODE" ] && [ -z "$RELEASE_PREFIX" ] && [ -z "$YES" ]; then
+    read -p "Release prefix [$DEFAULT_RELEASE_PREFIX]: " RELEASE_PREFIX
+  fi
+  if [ -z "$RELEASE_PREFIX" ]; then
     RELEASE_PREFIX=$DEFAULT_RELEASE_PREFIX
-fi
-if [ -n "$CONFIG_FILE_WRITE_MODE" ] && [ -z "$RELEASE_PREFIX" ] && [ -z "$YES" ]; then
-  read -p "Release prefix [$DEFAULT_RELEASE_PREFIX]: " RELEASE_PREFIX
-fi
-if [ -z "$RELEASE_PREFIX" ]; then
-  RELEASE_PREFIX=$DEFAULT_RELEASE_PREFIX
-fi
-if [[ ! $RELEASE_PREFIX =~ $PREFIX_PATTERN ]]; then
-  echo "ERROR: Invalid release prefix name ($RELEASE_PREFIX): only letters and numbers allowed!"; exit 1
-else
-  echo "  Using release prefix: $RELEASE_PREFIX"
-fi
+  fi
+  if [[ ! $RELEASE_PREFIX =~ $PREFIX_PATTERN ]]; then
+    echo "ERROR: Invalid release prefix name ($RELEASE_PREFIX): only letters and numbers allowed!"; exit 1
+  else
+    echo "  Using release prefix: $RELEASE_PREFIX"
+  fi
 
 
-# If in write mode, then writing out the configuration
-if [ -n "$CONFIG_FILE_WRITE_MODE" ] ; then
-  echo "" > "$CONFIG_FILE"    # first emptying the file
-  echo "AWS_PROFILE=$PROFILE" >> $CONFIG_FILE
-  echo "DIST_DIR=$DIST_DIR" >> $CONFIG_FILE
-  echo "S3_BUCKET=$S3_BUCKET" >> $CONFIG_FILE
-  echo "BACKUP_BUCKET=$BACKUP_BUCKET" >> $CONFIG_FILE
-  echo "RELEASE_PREFIX=$RELEASE_PREFIX" >> $CONFIG_FILE
-  # Adding the config file to .gitignore
-  if [ "$GITIGNORE" == "true" ]; then
-    if [ -f $BASE_DIR/.gitignore ]; then
-      if grep -q *.$CONFIG_FILE_TYPE $BASE_DIR/.gitignore 2>&1 ; then
-        :
+  # If in write mode, then writing out the configuration
+  if [ -n "$CONFIG_FILE_WRITE_MODE" ] ; then
+    echo "" > "$CONFIG_FILE"    # first emptying the file
+    echo "AWS_PROFILE=$PROFILE" >> $CONFIG_FILE
+    echo "DIST_DIR=$DIST_DIR" >> $CONFIG_FILE
+    echo "S3_BUCKET=$S3_BUCKET" >> $CONFIG_FILE
+    echo "BACKUP_BUCKET=$BACKUP_BUCKET" >> $CONFIG_FILE
+    echo "RELEASE_PREFIX=$RELEASE_PREFIX" >> $CONFIG_FILE
+    # Adding the config file to .gitignore
+    if [ "$GITIGNORE" == "true" ]; then
+      if [ -f $BASE_DIR/.gitignore ]; then
+        if grep -q *.$CONFIG_FILE_TYPE $BASE_DIR/.gitignore 2>&1 ; then
+          :
+        else
+          echo "" >> $BASE_DIR/.gitignore
+          echo "# distribution config file" >> $BASE_DIR/.gitignore
+          echo "*.$CONFIG_FILE_TYPE"  >> $BASE_DIR/.gitignore
+          echo "" >> $BASE_DIR/.gitignore
+          echo "The config file type is added to the .gitignore file."
+        fi
       else
-        echo "" >> $BASE_DIR/.gitignore
-        echo "# distribution config file" >> $BASE_DIR/.gitignore
-        echo "*.$CONFIG_FILE_TYPE"  >> $BASE_DIR/.gitignore
-        echo "" >> $BASE_DIR/.gitignore
-        echo "The config file type is added to the .gitignore file."
+        echo "If you will use Git in the future, you may add $CONFIG_FILE_NAME or *.$CONFIG_FILE_TYPE to your .gitignore file."
       fi
-    else
-      echo "If you will use Git in the future, you may add $CONFIG_FILE_NAME or *.$CONFIG_FILE_TYPE to your .gitignore file."
     fi
-  fi
-  # Give a note about how to use the command with the config
-  CCONFIG=""
-  if [ "$CONFIG_FILE_NAME" != "$CONFIG_FILE_NAME_DEFAULT" ]; then
-    CCONFIG=" -c $CONFIG_FILE_NAME"
+    # Give a note about how to use the command with the config
+    CCONFIG=""
+    if [ "$CONFIG_FILE_NAME" != "$CONFIG_FILE_NAME_DEFAULT" ]; then
+      CCONFIG=" -c $CONFIG_FILE_NAME"
+    fi
+
+    echo ""
+    echo "- Config file saved. -"
+    echo ""
+    echo "For uploading your site, you can use now the command:  dist_upload$CCONFIG"
+    echo ""
+    exit 0
   fi
 
-  echo ""
-  echo "- Config file saved. -"
-  echo ""
-  echo "For uploading your site, you can use now the command:  dist_upload$CCONFIG"
-  echo ""
-  exit 0
-fi
+fi # not UNDO mode
 
 
 # SYNC SECTION *********************************************************************************
@@ -398,7 +406,11 @@ if aws s3 ls $S3_BUCKET --profile $PROFILE  2>&1 | grep -q 'NoSuchBucket' ; then
   echo "ERROR: The given S3 bucket ($S3_BUCKET) does not exists or not reachable with the credentials set in the profile '$PROFILE!'"; exit 1
 else
   echo ""
-  echo "Starting the sync..."
+  if [ -z "$UNDO" ]; then
+    echo "Starting the sync..."
+  else
+    echo "Starting the recovery of the previous distribution version..."
+  fi
 fi
 # If backup bucket is not set, use the one read from settings file
 if [ -z "$BACKUP_BUCKET" ]; then
@@ -416,28 +428,37 @@ if [ "$BACKUP_BUCKET" != "off" ] ; then
       fi
     fi
     # Reading in existing release names
-    if VERSIONS=`aws s3 ls --profile $PROFILE s3://$BACKUP_BUCKET  | cut -c32- | grep / | tr -s '\n' ' '` | grep -q 'error'; then
-      echo "ERROR: Error reading backup bucket."; exit 1
-    fi
-    if [ -z "$VERSIONS" ]; then
-      MAX_VERSION=1
-    else
-      for VERS in $VERSIONS
-      do
-        MAX_VERSION=`echo $VERS | cut -d'-' -f 2`
-      done
-    fi
-    VERSION=$MAX_VERSION
-    echo "  Backing up existing distribution"
-    echo "    Using backup bucket: $BACKUP_BUCKET"
-    # Create release version id from epoc time
-    if [ -z "$RELEASE_VERSION" ]; then
-      RELEASE_VERSION="$RELEASE_PREFIX-$VERSION"
-    fi
-    echo "    Creating release version: $RELEASE_VERSION"
+    VERSIONS=`aws s3 ls --profile $PROFILE s3://$BACKUP_BUCKET  | cut -c32- | grep / | tr -s '\n' ' '`
+    # MAX_VERSION=0
+    # if [ -z "$VERSIONS" ]; then
+    #   MAX_VERSION=1
+    # else
+    #   for VERS in $VERSIONS
+    #   do
+    #     MAX_VERSION=`echo $VERS | cut -d'-' -f 2`
+    #   done
+    # fi
+    VERSION=`date '+%Y-%m-%d_%H:%M:%S'`
 
+    if [ -z "$UNDO" ]; then
+      echo "  Backing up existing distribution"
+      echo "    Using backup bucket: $BACKUP_BUCKET"
+      # Create release version id with prefix
+      if [ -z "$RELEASE_VERSION" ]; then
+        RELEASE_VERSION="$RELEASE_PREFIX/$VERSION"
+      fi
+      echo "    Creating release version: $RELEASE_VERSION"
+      if aws s3 cp $DIST_DIR s3://$BACKUP_BUCKET/$RELEASE_VERSION/  --recursive  --profile $PROFILE  --acl public-read 2>&1 > /dev/null | grep -q "error" ; then
+        echo "ERROR: Backup error: copy from dist folder to backup bucket has failed."; exit 1
+      fi
+    else    #UNDO mode
+      if [ -z "$VERSIONS" ]; then
+        echo "ERROR: No version is available to recover."; exit 1
+      fi
 
-fi
+    fi
+
+fi # backup == off
 
 
 # Getting the region from the profile
@@ -447,13 +468,23 @@ echo "Syncing $DIST_DIR -> S3://$S3_BUCKET"
 
 
 # Sync the dist files to S3
-if aws s3 sync $DIST_DIR s3://$S3_BUCKET --profile $PROFILE --delete --acl public-read | grep -q "error"; then
+if [ "$BACKUP_BUCKET" == "off" ] || [ "$BACKUP_BUCKET" != "$S3_BUCKET"  ]; then
+  if aws s3 sync $DIST_DIR s3://$S3_BUCKET --profile $PROFILE --delete --acl public-read 2>&1 > /dev/null | grep -q "error"; then
+    SYNC_ERROR="ERROR: Uploading to bucket has failed."
+  fi
+else
+  if [ "$BACKUP_BUCKET" == "$S3_BUCKET" ]; then
+    INDEX_HTML='<html><head><meta http-equiv="Refresh" content="0; URL=./$RELEASE_VERSION/"></head></html>'
+    echo $INDEX_HTML | aws s3 cp - s3://$S3_BUCKET/index.html --profile $PROFILE --acl public-read 
+  fi
+fi
+if [ -n "$SYNC_ERROR" ]; then
   echo "/////////////////////////////////////////////"
   echo "//                                         //"
   echo "//               WARNING !                 //"
   echo "//  File sync failed, upload unsuccesful!  //"
   echo "//                                         //"
-  echo "/////////////////////////////////////////////"; exit 1
+  echo "/////////////////////////////////////////////"; echo $SYNC_ERROR;  exit 1
 else
   echo "••••••••••••••••••••••••••••••••••••••••••••••••••••••••"
   echo "•                                                      •"
