Version patch

diff --git a/dist-upload-s3 b/dist-upload-s3
--- a/dist-upload-s3
+++ b/dist-upload-s3
@@ -28,7 +28,7 @@
 # **************************************************************************************************************************
 
 # Setting base variables
-VERSION="1.1.2"
+VERSION="1.1.3"
 BASE_DIR=$(dirname "$0")
 NAME_PATTERN="^[A-Za-z][A-Za-z0-9\-\_]+[A-Za-z]$" # regexp pattern for name checking
 CONFIG_FILE_NAME_DEFAULT="upload"    # Default name for the config file to save.
@@ -158,7 +158,8 @@ if [ -f "$CONFIG_FILE" ]; then
   done < "$CONFIG_FILE"
 else
   if [ "$CONFIG_WRITE_MODE" != true ]; then
-    echo "ERROR: Config file ($CONFIG_FILE_NAME) not found!"; exit 1
+    echo "ERROR: Config file ($CONFIG_FILE_NAME) not found!"
+    echo "Hint: Create a config file as the first step using  dist-upload-s3 -w"; exit 1
   fi
 fi
 
